GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhY2Nlc3MiLCJleHAiOjE1NDgwMDAwMDAsImlhdCI6MTU0NzAwMDAwMCwibmJmIjoxNTQ3MDAwMDAwLCJqdGkiOiIwMDkzN2MzOS0xMGFlLTRlMWEtYWQ5My1mNWZkOWRhN2I0ZGYiLCJ1c2VybmFtZSI6InRlc3QifQ.yZl49XoWeOhvFPNCVh_oa4iDvu7t43cm4vOtkB9vEvtZ8B1IFC3RaSkXqXVKQd8vGmMeoWLtEBuQZGZASrlyNA

###