GET http://localhost:8080/plans/2018/12/26
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhY2Nlc3MiLCJleHAiOjE1NDg5NjMxNDIsImlhdCI6MTU0ODk1Njc0MiwibmJmIjoxNTQ4OTU2NzQyLCJqdGkiOiIxYTFhZGViYS0wMzM4LTQxNzItYWJhOC0wYmIwNzcwNWJjNzciLCJ1c2VybmFtZSI6InRlc3QifQ.JFpkY_ZtbMNGbYdy7Z-nK69n3EaXUdGnL80_mzWSWZFLNZ6DNXtjabH1Yn3I5ipEWP7lWcMrrpL7oMRQP4EcKw

###