spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/planther
    username: root
    password: mocha127
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

jwt:
  access:
    exp: 6400000
  refresh:
    exp: 2592000000